name: "Variants demo using GitHub actions and quick-start"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    paths:
      - 'amulet_controller/*.kicad_sch'
      - 'amulet_controller/*.kicad_pcb'
      - '.github/workflows/kibot_action_quick_start.yml'
  pull_request:
    paths:
      - 'amulet_controller/*.kicad_sch'
      - 'amulet_controller/*.kicad_pcb'
      - '.github/workflows/kibot_action_quick_start.yml'
  repository_dispatch:
    types: [run_qs_gha]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  quick:
    name: "Quick Start (action)"
    runs-on: ubuntu-latest

    steps:
    - name: Get repo
      uses: actions/checkout@v3
      with:
        # So we can run a diff between last 2 changes
        fetch-depth: '0'

    - name: Run KiBot
      # v2_k6 for v1.5.1 has a permission problem
      uses: INTI-CMNB/KiBot@v2_dk7
      with:
        quickstart: YES

    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: Automatic_outputs
        path: Generated